#!/bin/bash
screen -S minecraft-server -X stuff 'stop\n' || screen -dmS minecraft-server && echo $(date) - screen crashed >> /home/user/Downloads/minecraft-server/server-log
sleep 180
screen -S minecraft-server -X stuff 'cd /home/user/Downloads/minecraft-server\n'
screen -S minecraft-server -X stuff 'SCRIPTSTARTED=$EPOCHSECONDS; while (( $EPOCHSECONDS < $SCRIPTSTARTED + 86100)); do java -Xmx1024M -Xms1024M -jar server.jar nogui; echo $(date) - server crashed >> server-log; done\n'

